language: python

python:
  - "2.6"
  - "2.7"

install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then sudo apt-get install -qq gdb python${TRAVIS_PYTHON_VERSION}-dbg; fi
  - python setup.py install

script: python setup.py test
